/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2017-07-26 06:12:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>电商后台 -登陆页面</title>\r\n");
      out.write("<meta name=\"Copyright\" content=\"Douco Design.\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/global.js\"></script>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/login.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"css/index_style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script src=\"http://www.jq22.com/jquery/jquery-1.10.2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("//宇宙特效\r\n");
      out.write("\"use strict\";\r\n");
      out.write("var canvas = document.getElementById('canvas'),\r\n");
      out.write("  ctx = canvas.getContext('2d'),\r\n");
      out.write("  w = canvas.width = window.innerWidth,\r\n");
      out.write("  h = canvas.height = window.innerHeight,\r\n");
      out.write("\r\n");
      out.write("  hue = 217,\r\n");
      out.write("  stars = [],\r\n");
      out.write("  count = 0,\r\n");
      out.write("  maxStars = 1300;//星星数量\r\n");
      out.write("\r\n");
      out.write("var canvas2 = document.createElement('canvas'),\r\n");
      out.write("  ctx2 = canvas2.getContext('2d');\r\n");
      out.write("canvas2.width = 100;\r\n");
      out.write("canvas2.height = 100;\r\n");
      out.write("var half = canvas2.width / 2,\r\n");
      out.write("  gradient2 = ctx2.createRadialGradient(half, half, 0, half, half, half);\r\n");
      out.write("gradient2.addColorStop(0.025, '#CCC');\r\n");
      out.write("gradient2.addColorStop(0.1, 'hsl(' + hue + ', 61%, 33%)');\r\n");
      out.write("gradient2.addColorStop(0.25, 'hsl(' + hue + ', 64%, 6%)');\r\n");
      out.write("gradient2.addColorStop(1, 'transparent');\r\n");
      out.write("\r\n");
      out.write("ctx2.fillStyle = gradient2;\r\n");
      out.write("ctx2.beginPath();\r\n");
      out.write("ctx2.arc(half, half, half, 0, Math.PI * 2);\r\n");
      out.write("ctx2.fill();\r\n");
      out.write("\r\n");
      out.write("// End cache\r\n");
      out.write("\r\n");
      out.write("function random(min, max) {\r\n");
      out.write("  if (arguments.length < 2) {\r\n");
      out.write("    max = min;\r\n");
      out.write("    min = 0;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  if (min > max) {\r\n");
      out.write("    var hold = max;\r\n");
      out.write("    max = min;\r\n");
      out.write("    min = hold;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  return Math.floor(Math.random() * (max - min + 1)) + min;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function maxOrbit(x, y) {\r\n");
      out.write("  var max = Math.max(x, y),\r\n");
      out.write("    diameter = Math.round(Math.sqrt(max * max + max * max));\r\n");
      out.write("  return diameter / 2;\r\n");
      out.write("  //星星移动范围，值越大范围越小，\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var Star = function() {\r\n");
      out.write("\r\n");
      out.write("  this.orbitRadius = random(maxOrbit(w, h));\r\n");
      out.write("  this.radius = random(60, this.orbitRadius) / 8; \r\n");
      out.write("  //星星大小\r\n");
      out.write("  this.orbitX = w / 2;\r\n");
      out.write("  this.orbitY = h / 2;\r\n");
      out.write("  this.timePassed = random(0, maxStars);\r\n");
      out.write("  this.speed = random(this.orbitRadius) / 50000; \r\n");
      out.write("  //星星移动速度\r\n");
      out.write("  this.alpha = random(2, 10) / 10;\r\n");
      out.write("\r\n");
      out.write("  count++;\r\n");
      out.write("  stars[count] = this;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("Star.prototype.draw = function() {\r\n");
      out.write("  var x = Math.sin(this.timePassed) * this.orbitRadius + this.orbitX,\r\n");
      out.write("    y = Math.cos(this.timePassed) * this.orbitRadius + this.orbitY,\r\n");
      out.write("    twinkle = random(10);\r\n");
      out.write("\r\n");
      out.write("  if (twinkle === 1 && this.alpha > 0) {\r\n");
      out.write("    this.alpha -= 0.05;\r\n");
      out.write("  } else if (twinkle === 2 && this.alpha < 1) {\r\n");
      out.write("    this.alpha += 0.05;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  ctx.globalAlpha = this.alpha;\r\n");
      out.write("  ctx.drawImage(canvas2, x - this.radius / 2, y - this.radius / 2, this.radius, this.radius);\r\n");
      out.write("  this.timePassed += this.speed;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("for (var i = 0; i < maxStars; i++) {\r\n");
      out.write("  new Star();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function animation() {\r\n");
      out.write("  ctx.globalCompositeOperation = 'source-over';\r\n");
      out.write("  ctx.globalAlpha = 0.5; //尾巴\r\n");
      out.write("  ctx.fillStyle = 'hsla(' + hue + ', 64%, 6%, 2)';\r\n");
      out.write("  ctx.fillRect(0, 0, w, h)\r\n");
      out.write("\r\n");
      out.write("  ctx.globalCompositeOperation = 'lighter';\r\n");
      out.write("  for (var i = 1, l = stars.length; i < l; i++) {\r\n");
      out.write("    stars[i].draw();\r\n");
      out.write("  };\r\n");
      out.write("\r\n");
      out.write("  window.requestAnimationFrame(animation);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("animation();\r\n");
      out.write("</script>\r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write("  \r\n");
      out.write("    $(function() {\r\n");
      out.write("    \t  $(\"#codeCheck\").change(function() {\r\n");
      out.write("    \t\t    var ajax = createAJAX();\r\n");
      out.write("    \t\t    var checkcode = this.value;\r\n");
      out.write("    \t        var method = \"POST\";\r\n");
      out.write("    \t        var url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/checkRequest!check.action?time=\"+new Date().getTime();\r\n");
      out.write("    \t        ajax.open(method,url);\r\n");
      out.write("    \t        //设置请求头（必须）\r\n");
      out.write("    \t        ajax.setRequestHeader(\"content-type\",\"application/x-www-form-urlencoded\");\r\n");
      out.write("\r\n");
      out.write("    \t        var content = \"checkcode=\" + checkcode;\r\n");
      out.write("    \t        ajax.send(content);\r\n");
      out.write("\r\n");
      out.write("    \t        ajax.onreadystatechange = function(){\r\n");
      out.write("    \t        \tif(ajax.readyState == 4){\r\n");
      out.write("    \t                if(ajax.status == 200){\r\n");
      out.write("    \t                    var tip = ajax.responseText;\r\n");
      out.write("    \t                    //alert(tip);\r\n");
      out.write("    \t                  if(tip==\"success\"){\r\n");
      out.write("    \t                \t/*  var img = document.createElement(\"img\");\r\n");
      out.write("    \t                     img.src = tip;\r\n");
      out.write("    \t                     //定位验证码文本框\r\n");
      out.write("    \t                     var td = document.getElementById(\"tishi\");\r\n");
      out.write("    \t                     td.innerHTML = \"验证码正确\"; */\r\n");
      out.write("    \t                     $(\"#tishi\").html(\"<font color='green'>验证码正确</font>\");\r\n");
      out.write("    \t                     }else {\r\n");
      out.write("    \t          \t\t       /*  var td = document.getElementById(\"tishi\");\r\n");
      out.write("    \t         \t\t        td.innerHTML = \"验证码错误\";\r\n");
      out.write("    \t         \t\t        td.appendChild(img);\r\n");
      out.write("    \t         \t\t        var t = document.getElementById(\"code\");\r\n");
      out.write("    \t         \t\t        t.innerHTML = \"\"; */\r\n");
      out.write("    \t         \t\t        $(\"#tishi\").html(\"<font color='red'>验证码错误</font>\");\r\n");
      out.write("    \t         \t\t        $(\"#codeCheck\").val(\"\");\r\n");
      out.write("    \t         \t\t        \r\n");
      out.write("    \t                  \r\n");
      out.write("    \t                }\r\n");
      out.write("    \t            }\r\n");
      out.write("    \t    }\r\n");
      out.write("    \t        };\r\n");
      out.write("    \t  });\r\n");
      out.write("\t });\r\n");
      out.write("</script> \r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("function huan(x)\r\n");
      out.write("{\r\n");
      out.write("\tx.src=\"code.jsp?time\"+new Date();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function createAJAX(){\r\n");
      out.write("\tvar ajax = null;\r\n");
      out.write("\ttry{\r\n");
      out.write("\tajax = new ActiveXObject(\"microsoft.xmlhttp\");\r\n");
      out.write("\t}catch(e1){\r\n");
      out.write("\ttry{\r\n");
      out.write("\tajax = new XMLHttpRequest();\r\n");
      out.write("\t}catch(e2){\r\n");
      out.write("\talert(\"你的浏览器不支持ajax，请更换浏览器\");\r\n");
      out.write("\t}\r\n");
      out.write("\t}\r\n");
      out.write("\treturn ajax;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"header\" id=\"demo\">\r\n");
      out.write("    \t\r\n");
      out.write("    \r\n");
      out.write("  <div class=\"canvaszz\"> \r\n");
      out.write("  <div class=\"title\" align=\"center\" style=\"margin-top: 100px;\">\r\n");
      out.write("  <form method=\"post\"  action=\"UserActionyc!login.action\" >\r\n");
      out.write("\t\t\t<font size=\"6px\" style=\"color: white\">管理登录</font><br /><br /><br />\r\n");
      out.write("\t\t\t<label for=\"input1\"><font size=\"3px\" style=\"color: white\">用户账号</font></label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"user.username\" id=\"input1\" /><br /><br /><br />\r\n");
      out.write("\t\t\t<label for=\"input2\"><font size=\"3px\" style=\"color: white\">账户密码</font></label> <input type=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"user.password\" id=\"input2\" /><br /><br /><br />\r\n");
      out.write("\t\t\t<label for=\"code\"><font size=\"3px\" style=\"color: white;margin-left: 125px;\">验证码</font></label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 120px;\" name=\"code\" id=\"codeCheck\" maxlength=\"6\"  />\t\r\n");
      out.write("\t\t\t<img id=\"safecode\" onclick=\"huan(this)\" alt=\"点击换一张\" title=\"点击换一张\" src=\"code.jsp\" style=\"width: 120px;height: 25px;margin-left: 5px;position: relative;top: 5px;\"/>\t<br /><br /><br />\t\t\t\t\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"登陆\" style=\"width: 100px;margin-left: 60px;\" />\r\n");
      out.write("\t\t\t\t\t</form>\t\t\r\n");
      out.write("\t       </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <canvas id=\"canvas\"></canvas> \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("//宇宙特效\r\n");
      out.write("\"use strict\";\r\n");
      out.write("var canvas = document.getElementById('canvas'),\r\n");
      out.write("  ctx = canvas.getContext('2d'),\r\n");
      out.write("  w = canvas.width = window.innerWidth,\r\n");
      out.write("  h = canvas.height = window.innerHeight,\r\n");
      out.write("\r\n");
      out.write("  hue = 217,\r\n");
      out.write("  stars = [],\r\n");
      out.write("  count = 0,\r\n");
      out.write("  maxStars = 1300;//星星数量\r\n");
      out.write("\r\n");
      out.write("var canvas2 = document.createElement('canvas'),\r\n");
      out.write("  ctx2 = canvas2.getContext('2d');\r\n");
      out.write("canvas2.width = 100;\r\n");
      out.write("canvas2.height = 100;\r\n");
      out.write("var half = canvas2.width / 2,\r\n");
      out.write("  gradient2 = ctx2.createRadialGradient(half, half, 0, half, half, half);\r\n");
      out.write("gradient2.addColorStop(0.025, '#CCC');\r\n");
      out.write("gradient2.addColorStop(0.1, 'hsl(' + hue + ', 61%, 33%)');\r\n");
      out.write("gradient2.addColorStop(0.25, 'hsl(' + hue + ', 64%, 6%)');\r\n");
      out.write("gradient2.addColorStop(1, 'transparent');\r\n");
      out.write("\r\n");
      out.write("ctx2.fillStyle = gradient2;\r\n");
      out.write("ctx2.beginPath();\r\n");
      out.write("ctx2.arc(half, half, half, 0, Math.PI * 2);\r\n");
      out.write("ctx2.fill();\r\n");
      out.write("\r\n");
      out.write("// End cache\r\n");
      out.write("\r\n");
      out.write("function random(min, max) {\r\n");
      out.write("  if (arguments.length < 2) {\r\n");
      out.write("    max = min;\r\n");
      out.write("    min = 0;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  if (min > max) {\r\n");
      out.write("    var hold = max;\r\n");
      out.write("    max = min;\r\n");
      out.write("    min = hold;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  return Math.floor(Math.random() * (max - min + 1)) + min;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function maxOrbit(x, y) {\r\n");
      out.write("  var max = Math.max(x, y),\r\n");
      out.write("    diameter = Math.round(Math.sqrt(max * max + max * max));\r\n");
      out.write("  return diameter / 2;\r\n");
      out.write("  //星星移动范围，值越大范围越小，\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var Star = function() {\r\n");
      out.write("\r\n");
      out.write("  this.orbitRadius = random(maxOrbit(w, h));\r\n");
      out.write("  this.radius = random(60, this.orbitRadius) / 8; \r\n");
      out.write("  //星星大小\r\n");
      out.write("  this.orbitX = w / 2;\r\n");
      out.write("  this.orbitY = h / 2;\r\n");
      out.write("  this.timePassed = random(0, maxStars);\r\n");
      out.write("  this.speed = random(this.orbitRadius) / 50000; \r\n");
      out.write("  //星星移动速度\r\n");
      out.write("  this.alpha = random(2, 10) / 10;\r\n");
      out.write("\r\n");
      out.write("  count++;\r\n");
      out.write("  stars[count] = this;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("Star.prototype.draw = function() {\r\n");
      out.write("  var x = Math.sin(this.timePassed) * this.orbitRadius + this.orbitX,\r\n");
      out.write("    y = Math.cos(this.timePassed) * this.orbitRadius + this.orbitY,\r\n");
      out.write("    twinkle = random(10);\r\n");
      out.write("\r\n");
      out.write("  if (twinkle === 1 && this.alpha > 0) {\r\n");
      out.write("    this.alpha -= 0.05;\r\n");
      out.write("  } else if (twinkle === 2 && this.alpha < 1) {\r\n");
      out.write("    this.alpha += 0.05;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  ctx.globalAlpha = this.alpha;\r\n");
      out.write("  ctx.drawImage(canvas2, x - this.radius / 2, y - this.radius / 2, this.radius, this.radius);\r\n");
      out.write("  this.timePassed += this.speed;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("for (var i = 0; i < maxStars; i++) {\r\n");
      out.write("  new Star();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function animation() {\r\n");
      out.write("  ctx.globalCompositeOperation = 'source-over';\r\n");
      out.write("  ctx.globalAlpha = 0.5; //尾巴\r\n");
      out.write("  ctx.fillStyle = 'hsla(' + hue + ', 64%, 6%, 2)';\r\n");
      out.write("  ctx.fillRect(0, 0, w, h)\r\n");
      out.write("\r\n");
      out.write("  ctx.globalCompositeOperation = 'lighter';\r\n");
      out.write("  for (var i = 1, l = stars.length; i < l; i++) {\r\n");
      out.write("    stars[i].draw();\r\n");
      out.write("  };\r\n");
      out.write("\r\n");
      out.write("  window.requestAnimationFrame(animation);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("animation();\r\n");
      out.write("</script>\r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write("  \r\n");
      out.write("    $(function() {\r\n");
      out.write("    \t  $(\"#codeCheck\").change(function() {\r\n");
      out.write("    \t\t    var ajax = createAJAX();\r\n");
      out.write("    \t\t    var checkcode = this.value;\r\n");
      out.write("    \t        var method = \"POST\";\r\n");
      out.write("    \t        var url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/checkRequest!check.action?time=\"+new Date().getTime();\r\n");
      out.write("    \t        ajax.open(method,url);\r\n");
      out.write("    \t        //设置请求头（必须）\r\n");
      out.write("    \t        ajax.setRequestHeader(\"content-type\",\"application/x-www-form-urlencoded\");\r\n");
      out.write("\r\n");
      out.write("    \t        var content = \"checkcode=\" + checkcode;\r\n");
      out.write("    \t        ajax.send(content);\r\n");
      out.write("\r\n");
      out.write("    \t        ajax.onreadystatechange = function(){\r\n");
      out.write("    \t        \tif(ajax.readyState == 4){\r\n");
      out.write("    \t                if(ajax.status == 200){\r\n");
      out.write("    \t                    var tip = ajax.responseText;\r\n");
      out.write("    \t                    //alert(tip);\r\n");
      out.write("    \t                  if(tip==\"success\"){\r\n");
      out.write("    \t                \t/*  var img = document.createElement(\"img\");\r\n");
      out.write("    \t                     img.src = tip;\r\n");
      out.write("    \t                     //定位验证码文本框\r\n");
      out.write("    \t                     var td = document.getElementById(\"tishi\");\r\n");
      out.write("    \t                     td.innerHTML = \"验证码正确\"; */\r\n");
      out.write("    \t                     $(\"#tishi\").html(\"<font color='green'>验证码正确</font>\");\r\n");
      out.write("    \t                     }else {\r\n");
      out.write("    \t          \t\t       /*  var td = document.getElementById(\"tishi\");\r\n");
      out.write("    \t         \t\t        td.innerHTML = \"验证码错误\";\r\n");
      out.write("    \t         \t\t        td.appendChild(img);\r\n");
      out.write("    \t         \t\t        var t = document.getElementById(\"code\");\r\n");
      out.write("    \t         \t\t        t.innerHTML = \"\"; */\r\n");
      out.write("    \t         \t\t        $(\"#tishi\").html(\"<font color='red'>验证码错误</font>\");\r\n");
      out.write("    \t         \t\t        $(\"#codeCheck\").val(\"\");\r\n");
      out.write("    \t         \t\t        \r\n");
      out.write("    \t                  \r\n");
      out.write("    \t                }\r\n");
      out.write("    \t            }\r\n");
      out.write("    \t    }\r\n");
      out.write("    \t        };\r\n");
      out.write("    \t  });\r\n");
      out.write("\t });\r\n");
      out.write("</script> \r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("function huan(x)\r\n");
      out.write("{\r\n");
      out.write("\tx.src=\"code.jsp?time\"+new Date();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function createAJAX(){\r\n");
      out.write("\tvar ajax = null;\r\n");
      out.write("\ttry{\r\n");
      out.write("\tajax = new ActiveXObject(\"microsoft.xmlhttp\");\r\n");
      out.write("\t}catch(e1){\r\n");
      out.write("\ttry{\r\n");
      out.write("\tajax = new XMLHttpRequest();\r\n");
      out.write("\t}catch(e2){\r\n");
      out.write("\talert(\"你的浏览器不支持ajax，请更换浏览器\");\r\n");
      out.write("\t}\r\n");
      out.write("\t}\r\n");
      out.write("\treturn ajax;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
