/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2017-07-14 07:21:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class statisticalcontrol_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Head.jsp", Long.valueOf(1499992423675L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>DouPHP 管理中心 - 文章分类 </title>\r\n");
      out.write("<meta name=\"Copyright\" content=\"Douco Design.\" />\r\n");
      out.write("<link href=\"css/public.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"css/statisticalcontrol.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/global.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/echarts.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/china.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/sta_dao.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/sta_option_factory.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/statisticalcontrol.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"dcWrap\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>电商后台 -管理中心</title>\r\n");
      out.write("<meta name=\"Copyright\" content=\"Douco Design.\" />\r\n");
      out.write("<link href=\"css/public.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/global.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <div id=\"dcHead\">\r\n");
      out.write("\t<div id=\"head\">\r\n");
      out.write("  \t<div class=\"logo\"><a href=\"index.jsp\"><img src=\"images/dclogo.gif\" alt=\"logo\"></a></div>\r\n");
      out.write("  \t<div class=\"nav\">\r\n");
      out.write("   \t<ul>\r\n");
      out.write("    \t<li class=\"M\"><a href=\"JavaScript:void(0);\" class=\"topAdd\">新建</a>\r\n");
      out.write("     \t\t<div class=\"drop mTopad\"><a href=\"product.php?rec=add\">商品</a> <a href=\"article.php?rec=add\">文章</a> <a href=\"nav.php?rec=add\">自定义导航</a> <a href=\"show.jsp\">首页幻灯</a> <a href=\"page.php?rec=add\">单页面</a> <a href=\"manager.php?rec=add\">管理员</a> <a href=\"link.jsp\"></a> </div>\r\n");
      out.write("    \t</li>\r\n");
      out.write("    \t<li><a href=\"../index.php\" target=\"_blank\">查看站点</a></li>\r\n");
      out.write("    \t<li><a href=\"index.php?rec=clear_cache\">清除缓存</a></li>\r\n");
      out.write("    \t<li><a href=\"http://www.mycodes.net\" target=\"_blank\">帮助</a></li>\r\n");
      out.write("    \t<li class=\"noRight\"><a href=\"module.jsp\">DouPHP+</a></li>\r\n");
      out.write("   \t</ul>\r\n");
      out.write("    <ul class=\"navRight\">\r\n");
      out.write("    \t<li class=\"M noLeft\"><a href=\"JavaScript:void(0);\">您好，admin</a>\r\n");
      out.write("     \t\t<div class=\"drop mUser\">\r\n");
      out.write("      \t\t<a href=\"manager.php?rec=edit&id=1\">编辑我的个人资料</a>\r\n");
      out.write("      \t\t<a href=\"manager.php?rec=cloud_account\">设置云账户</a>\r\n");
      out.write("     \t\t</div>\r\n");
      out.write("    \t</li>\r\n");
      out.write("    \t<li class=\"noRight\"><a href=\"login.php?rec=logout\">退出</a></li>\r\n");
      out.write("   </ul>\r\n");
      out.write("   </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- dcHead 结束 --> \r\n");
      out.write("\r\n");
      out.write("<div id=\"dcLeft\"><div id=\"menu\">\r\n");
      out.write("\t<ul class=\"top\">\r\n");
      out.write("  \t\t<li><a href=\"index.jsp\"><i class=\"home\"></i><em>管理首页</em></a></li>\r\n");
      out.write(" \t</ul>\r\n");
      out.write(" \t<ul>\r\n");
      out.write("  \t\t<li><a href=\"system.jsp\"><i class=\"system\"></i><em>系统设置</em></a></li>\r\n");
      out.write("  \t\t<li><a href=\"usercenter.jsp\"><i class=\"nav\"></i><em>用户中心</em></a></li>\r\n");
      out.write("  \t\t<li><a href=\"usercontrol.jsp\"><i class=\"show\"></i><em>用户管理</em></a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("    <ul>\r\n");
      out.write("\t\t<li><a href=\"ordercontrol.jsp\"><i class=\"productCat\"></i><em>订单管理</em></a></li>\r\n");
      out.write("\t  \t<li><a href=\"goodcontrol.jsp\"><i class=\"product\"></i><em>商品管理</em></a>\r\n");
      out.write("\t  \t\t<ul>\r\n");
      out.write("\t  \t\t\t<li><a href=\"usercenter.jsp\"><i class=\"nav\"></i><em>用户中心</em></a></li>\r\n");
      out.write("  \t\t\t\t<li><a href=\"usercontrol.jsp\"><i class=\"show\"></i><em>用户管理</em></a></li>\r\n");
      out.write("\t  \t\t</ul>\r\n");
      out.write("\t  \t</li>\r\n");
      out.write(" \t</ul>\r\n");
      out.write("  \t<ul>\r\n");
      out.write("  \t\t<li><a href=\"statistical!index.action\"><i class=\"articleCat\"></i><em>统计管理</em></a></li>\r\n");
      out.write("  \t\t<li><a href=\"noticecontrol.jsp\"><i class=\"article\"></i><em>公告管理</em></a></li>\r\n");
      out.write(" \t</ul>\r\n");
      out.write(" \t<ul class=\"bot\">\r\n");
      out.write("  \t\t<li><a href=\"shujubfnoticecontrol.jsp\"><i class=\"backup\"></i><em>数据备份</em></a></li>\r\n");
      out.write("  \t\t<li><a href=\"manager.jsp\"><i class=\"manager\"></i><em>网站管理员</em></a></li>\r\n");
      out.write(" \t</ul>\r\n");
      out.write("</div></div>\r\n");
      out.write("<!-- 左侧导航栏结束 -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<div id=\"dcMain\">\r\n");
      out.write("\t<div id=\"urHere\">FiveGroup 管理中心<b>></b><strong>统计管理</strong> </div>   \r\n");
      out.write("\t<div class=\"mainBox\" style=\"height:auto!important;height:550px;min-height:550px;\">\r\n");
      out.write("        <div id=\"date_distribution\"></div><br/>\r\n");
      out.write("        <div id=\"addr_distribution\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"clear\"></div>\r\n");
      out.write("<div id=\"dcFooter\">\r\n");
      out.write("\t<div id=\"footer\">\r\n");
      out.write("  \t<div class=\"line\"></div>\r\n");
      out.write(" \t</div>\r\n");
      out.write("</div><!-- dcFooter 结束 -->\r\n");
      out.write("<div class=\"clear\"></div> </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
