
CREATE TABLE ADDRESS
(
	ADDRESSID INT NOT NULL AUTO_INCREMENT COMMENT '地址ID',
	PROVINCE VARCHAR(20) NOT NULL UNIQUE COMMENT '省份',
	CITY VARCHAR(20) NOT NULL COMMENT '城市',
	AREA VARCHAR(20) NOT NULL COMMENT '区域',
	STREET VARCHAR(200) COMMENT '�街道',
	DETAIL VARCHAR(200) COMMENT '详细地址',
	TEL VARCHAR(11) NOT NULL COMMENT '电话号码',
	USER VARCHAR(20) COMMENT '用户名',
	USERID INT NOT NULL COMMENT '用户ID',
	PRIMARY KEY (ADDRESSID)
) COMMENT = '地址信息表';



CREATE TABLE ORDERITEMS
(
	ORDERITEMID INT NOT NULL AUTO_INCREMENT COMMENT '订单详情ID',
	COUNT INT NOT NULL COMMENT '数量',
	DISCOUNT FLOAT NOT NULL COMMENT '折扣',
	ORDERID INT NOT NULL COMMENT '订单ID',
	PRODUCTID INT NOT NULL COMMENT '商品ID',
	PRIMARY KEY (ORDERITEMID)
) COMMENT = '订单详情表';


CREATE TABLE ORDERS
(
	ORDERID INT NOT NULL AUTO_INCREMENT COMMENT '订单ID',
	TIME DATETIME NOT NULL COMMENT '订单时间',
	STATUS INT NOT NULL COMMENT '״订单状态',
	USERID INT NOT NULL COMMENT '用户ID',
	ADDRESSID INT NOT NULL COMMENT '地址ID',
	PRIMARY KEY (ORDERID)
) COMMENT = '订单表';



CREATE TABLE PRODUCT
(
	PRODUCTID INT NOT NULL AUTO_INCREMENT COMMENT '商品ID',
	NAME VARCHAR(100) NOT NULL COMMENT '名字',
	BRAND VARCHAR(20) NOT NULL COMMENT '品牌',
	TYPE VARCHAR(10) NOT NULL COMMENT '类型',
	SERIS VARCHAR(20) NOT NULL COMMENT '分类',
	DESCRIPTION VARCHAR(1000) COMMENT '描述',
	BASICPRICE FLOAT NOT NULL COMMENT '价格',
	TYPEID INT NOT NULL COMMENT '类型ID',
	image VARCHAR(25) NOT NULL COMMENT '图片',
	PRIMARY KEY (PRODUCTID)
) ENGINE = InnoDB COMMENT = '商品表';



CREATE TABLE PRODUCTIMAGE
(
	PRODUCTIMAGEID INT NOT NULL AUTO_INCREMENT COMMENT '商品图片',
	PATH VARCHAR(20) NOT NULL COMMENT '图片路径',
	ENABLE BIT(1) NOT NULL COMMENT '是否可用',
	PRODUCTID INT NOT NULL COMMENT '商品ID',
	PRIMARY KEY (PRODUCTIMAGEID)
) COMMENT = '存储图片路径表';



CREATE TABLE PRODUCTMODELTYPE
(
	MODELTYPEID INT NOT NULL AUTO_INCREMENT COMMENT '商品类型ID',
	SIZE VARCHAR(20) NOT NULL COMMENT '大小',
	COLOR VARCHAR(20) NOT NULL COMMENT '颜色',
	PRICE FLOAT NOT NULL COMMENT '价格',
	COUNTS INT COMMENT '数量',
	PRODUCTID INT NOT NULL COMMENT '商品ID',
	PRIMARY KEY (MODELTYPEID)
) COMMENT = '商品选择表';



CREATE TABLE PRODUCTTYPE
(
	PRODUCTTYPEID INT NOT NULL AUTO_INCREMENT COMMENT '商品ID',
	TYPENAME VARCHAR(20) NOT NULL COMMENT '类型名称',
	PRIMARY KEY (PRODUCTTYPEID)
) COMMENT = '商品类型表';



CREATE TABLE USERS
(
	USERID INT NOT NULL AUTO_INCREMENT COMMENT '用户ID',
	USERNAME VARCHAR(20) NOT NULL UNIQUE COMMENT '用户名',
	PASSWORD VARCHAR(30) NOT NULL COMMENT '密码',
	REALNAME VARCHAR(20) NOT NULL COMMENT '真实姓名',
	SEX BIT(1) COMMENT '性别',
	AGE INT COMMENT '年龄',
	IMAGE VARCHAR(50) COMMENT '头像',
	STATUS BIT(1) COMMENT '״状态',
	PRIMARY KEY (USERID)
) ENGINE = InnoDB COMMENT = '用户表' DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;




ALTER TABLE ORDERS
	ADD FOREIGN KEY (ADDRESSID)
	REFERENCES ADDRESS (ADDRESSID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ORDERITEMS
	ADD FOREIGN KEY (ORDERID)
	REFERENCES ORDERS (ORDERID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ORDERITEMS
	ADD FOREIGN KEY (PRODUCTID)
	REFERENCES PRODUCT (PRODUCTID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PRODUCTIMAGE
	ADD FOREIGN KEY (PRODUCTID)
	REFERENCES PRODUCT (PRODUCTID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PRODUCTMODELTYPE
	ADD FOREIGN KEY (PRODUCTID)
	REFERENCES PRODUCT (PRODUCTID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PRODUCT
	ADD FOREIGN KEY (TYPEID)
	REFERENCES PRODUCTTYPE (PRODUCTTYPEID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ADDRESS
	ADD FOREIGN KEY (USERID)
	REFERENCES USERS (USERID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ORDERS
	ADD FOREIGN KEY (USERID)
	REFERENCES USERS (USERID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

/*更改表名字
alter table ADDRESS rename address;
alter table ORDERITEMS rename orderitems;
alter table ORDERS rename orders;
alter table PRODUCT rename product;
alter table PRODUCTIMAGE rename productimage;
alter table PRODUCTMODELTYPE rename productmodeltype;
alter table PRODUCTTYPE rename producttype;
alter table USERS rename users;
*/
